version: "3"

services:

  runtime-setup:
    image: async-http-client:16.04-5.2
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.2"

  test:
    image: async-http-client:16.04-5.2
    environment:
      - SANITIZER_ARG=--sanitize=thread
      - TEST_DISCOVERY=--enable-test-discovery
    

  shell:
    image: async-http-client:16.04-5.2
