version: "3"

services:

  runtime-setup:
    image: async-http-client:22.04-5.7
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.7"

  documentation-check:
    image: async-http-client:22.04-5.7

  test:
    image: async-http-client:22.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: async-http-client:22.04-5.7
