version: "3"

services:

  runtime-setup:
    image: async-http-client:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  documentation-check:
    image: async-http-client:22.04-main

  test:
    image: async-http-client:22.04-main
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: async-http-client:22.04-main
